#[cfg(test)]
use super::*;

mod data_state_test;
mod end_tag_open_state_test;
mod plaintext_state_test;
mod rawtext_end_tag_name_state_test;
mod rawtext_end_tag_open_state_test;
mod rawtext_less_than_sign_state_test;
mod rawtext_state_test;
mod rcdata_end_tag_name_state_test;
mod rcdata_end_tag_open_state_test;
mod rcdata_less_than_sign_state_test;
mod rcdata_state_test;
mod script_data_end_tag_name_state_test;
mod script_data_end_tag_open_state_test;
mod script_data_escape_start_dash_state_test;
mod script_data_escape_start_state_test;
mod script_data_escaped_dash_dash_state_test;
mod script_data_escaped_dash_state_test;
mod script_data_escaped_less_than_sign_state_test;
mod script_data_escaped_state_test;
mod script_data_less_than_sign_state_test;
mod script_data_state_test;
mod tag_name_state_test;
mod tag_open_state_test;
